---
- name: commands
  hosts: Windows
  
  tasks:
    - name: run a program
      ansible.windows.win_command: ping windc.example.com
      args:
        chdir: c:\windows\temp
      changed_when: false
      ignore_errors: true

    - name: run some powershell stuff
      ansible.windows.win_shell: |
        $app = GetWmiObject -Class Win32_Product | Where-Object { 
            $_.Name -match "7-Zip 19.00 (x64 edition)" 
            }
        $app.Uninstall()
      ignore_errors: true

    - name: copy a script
      ansible.builtin.script: script.ps1
      ignore_errors: true

    - name: create a scheduled task
      community.windows.win_scheduled_task:
        name: mytask
        triggers:
          - type: boot
          - type: daily
            start_boundary: "2025-01-01T09:00:00"
        actions:
          - path: ping.exe
            arguments: windc.example.com
        username: SYSTEM
        state: present



    
