---
- name: play to mitigate PrintNightmare
  hosts: Windows
  tasks:
    - name: disable spooler service
      ansible.windows.win_service:
        name: Spooler
        state: stopped
        start_mode: disabled

    - name: ensure update is installed
      ansible.windows.win_updates:
        accept_list: KB5012647
        state: installed

    - name: apply a registry vavlue
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint
        state: absent
        delete_key: true

- name: second play
  hosts: Texas
  tasks:
    - name: this only runs in Texas
      ansible.builtin.debug:
        msg: Hello World

    - name: create a file in Texas
      ansible.builtin.win_copy:
        content: |
          this is in my string
          this is still in my string
          here's more string
             don't care about "  ' " whatever
             {} also fine
        dest: c:\windows\temp\hello.txt






