---
- name: mitigate PrintNightmare
  hosts: Windows
  max_fail_percentage: 25
  tasks:

    - name: stop the Spooler service
      ansible.windows.win_service:
        name: Spooler
        state: stopped
        start_mode: disabled

    - name: install update
      ansible.windows.win_updates:
        accept_list: 5012647
        state: installed

    - name: setting a registry key
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint
        name: NoWarningNoElevationOnInstall
        type: dword
        value: 0

- name: another play to target win1
  hosts: win1.example.com
  become: true
  become_method: runas
  tasks:
    - name: different target 
      ansible.windows.win_ping:

    - name: copied out hello world
      ansible.windows.win_copy:
        content: >
          Hello world
          this is one line
          but it's really long
          "" do not matter
        dest: C:\WINDOWS\TEMP\HELLO.TXT

    - name: run a powershell commands
      ansible.windows.win_shell: |
        Get-LocalUser
        Get-WmiObject -Class Win32_Product
      args:
        chdir: c:\temp



    


...