---
- name: mitigate Spectre
  hosts: Windows
  vars:
    memoryValues:
      - name: FeatureSettingsOverride
        data: 0
      - name: FeatureSettingsOverrideMask
        data: 3
  tasks:
    - name: set both vvalues
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
        name: "{{ item['name'] }}"
        type: dword
        data: "{{ item['data'] }}"
      loop: "{{ memoryValues }}"

    - name: copy out .reg
      ansible.windows.win_copy:
        src: 7zip.reg
        dest: c:\windows\temp

    - name: delete the key first
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\7-zip
        state: absent
        delete_key: true

    - name: merge that to registry
      community.windows.win_regmerge:
        path: c:\windows\temp\7zip.reg


